exports = {
  camelize: requirejs('camelize.js'),
  capitalize: requirejs('capitalize.js'),
  clone: requirejs('clone.js'),
  concat: requirejs('concat.js'),
  contains: requirejs('contains.js'),
  dasherize: requirejs('dasherize.js'),
  each: requirejs('each.js'),
  empty: requirejs('empty.js'),
  extend: requirejs('extend.js'),
  flatten: requirejs('flatten.js'),
  format: requirejs('format.js'),
  indexOf: requirejs('indexOf.js'),
  isArray: requirejs('isArray.js'),
  isArrayLike: requirejs('isArrayLike.js'),
  isObject: requirejs('isObject.js'),
  isPlainObject: requirejs('isPlainObject.js'),
  keep: requirejs('keep.js'),
  keys: requirejs('keys.js'),
  map: requirejs('map.js'),
  reduce: requirejs('reduce.js'),
  remove: requirejs('remove.js'),
  runFunctions: requirejs('runFunctions.js'),
  sortBy: requirejs('sortBy.js'),
  words: requirejs('words.js')
};
